spring:
  application:
    name: socialising
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/socialising_db
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_ADDRESS:http://localhost:8761/eureka}
  instance:
    hostname: socialising
    prefer-ip-address: true

jwt:
  secret: 9RLtDzsDcwb67990ssdq

default:
  password: 123456@$2021


paging:
  default:
    page: 0
    size: 20

file:
  download_dir: "./downloads"
  upload_dir: "./uploads"

google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=

logging:
  level:
    org.springframework.cache: error
  file:
    name: logs/socialising
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7


kafka:
  bootstrap-servers: ${KAFKA_SERVERS:stc:9094}
  topic:
    email-no-template: email-no-template
    email-with-template: email-with-template
    email-with-attachment: email-with-attachment

twilio:
  account-sid: ACbfacc48411e45c587c9308aee50d4822
  account-password: cb395b46a394289980946561929c7b11
  account-from-number: +14157293681

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 1200000
  eager-load:
    enabled: true
    clients: service-bar

otp:
  ExpriedTime: 900

server:
  error:
    include-message: always
  port: 8080
